/**
 * TypeScript client for the escrow Anchor program.
 * Students use this to interact with the escrow PDA without needing Rust.
 *
 * Usage:
 *   import { initializeEscrow, claimEscrow, refundEscrow, findEscrowPda } from './escrow_client.js'
 */

import * as anchor from '@coral-xyz/anchor'
import { Program, BN } from '@coral-xyz/anchor'
import { PublicKey, Keypair, Connection, LAMPORTS_PER_SOL } from '@solana/web3.js'

// IDL type (generated by `anchor build` — commit the idl/ dir after building)
export type Escrow = {
  version: '0.1.0'
  name: 'escrow'
  instructions: [
    { name: 'initialize'; args: [{ name: 'amount'; type: 'u64' }, { name: 'memo'; type: 'string' }, { name: 'deadline'; type: 'i64' }] },
    { name: 'claim'; args: [] },
    { name: 'refund'; args: [] },
  ]
  accounts: [
    {
      name: 'escrowState'
      type: {
        kind: 'struct'
        fields: [
          { name: 'buyer'; type: 'publicKey' },
          { name: 'seller'; type: 'publicKey' },
          { name: 'amount'; type: 'u64' },
          { name: 'memo'; type: 'string' },
          { name: 'deadline'; type: 'i64' },
          { name: 'bump'; type: 'u8' },
        ]
      }
    },
  ]
  errors: [
    { code: 6000; name: 'ZeroAmount' },
    { code: 6001; name: 'MemoTooLong' },
    { code: 6002; name: 'DeadlinePassed' },
    { code: 6003; name: 'DeadlineNotPassed' },
  ]
}

export const ESCROW_PROGRAM_ID = new PublicKey('Escr1111111111111111111111111111111111111111')

export function findEscrowPda(buyer: PublicKey, memo: string, programId = ESCROW_PROGRAM_ID): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('escrow'), buyer.toBuffer(), Buffer.from(memo)],
    programId,
  )
}

export interface EscrowParams {
  program: Program<Escrow>
  buyer: Keypair
  seller: PublicKey
  amountSol: number
  memo: string
  deadlineSeconds?: number // defaults to 1 hour from now
}

/** Buyer deposits SOL into escrow PDA. Returns the escrow PDA address. */
export async function initializeEscrow(params: EscrowParams): Promise<PublicKey> {
  const { program, buyer, seller, amountSol, memo, deadlineSeconds = 3600 } = params
  const amount = Math.round(amountSol * LAMPORTS_PER_SOL)
  const deadline = Math.floor(Date.now() / 1000) + deadlineSeconds

  const [escrowPda] = findEscrowPda(buyer.publicKey, memo, program.programId)

  await program.methods
    .initialize(new BN(amount), memo, new BN(deadline))
    .accounts({ buyer: buyer.publicKey, seller })
    .signers([buyer])
    .rpc()

  return escrowPda
}

/** Seller claims funds from escrow after delivering service. */
export async function claimEscrow(
  program: Program<Escrow>,
  seller: Keypair,
  escrowPda: PublicKey,
): Promise<string> {
  return program.methods
    .claim()
    .accounts({ seller: seller.publicKey, escrow: escrowPda })
    .signers([seller])
    .rpc()
}

/** Buyer reclaims funds from escrow after the deadline has passed. */
export async function refundEscrow(
  program: Program<Escrow>,
  buyer: Keypair,
  escrowPda: PublicKey,
): Promise<string> {
  return program.methods
    .refund()
    .accounts({ buyer: buyer.publicKey, escrow: escrowPda })
    .signers([buyer])
    .rpc()
}

/** Read current escrow state from on-chain. */
export async function getEscrowState(program: Program<Escrow>, escrowPda: PublicKey) {
  return program.account.escrowState.fetch(escrowPda)
}
